# Lab 4 - Projections and Orthogonalizations

This lab will have you work through defining several functions that build up the basic operations of projection and orthogonalization.

You should probably never use YOUR functions in the future (other packages will be better optimized and better error-checked). This is simply to reinforce the understanding of these operations.

### Task 4.1 - Computing the Parallel Projection, in parts.

In [48]:
import numpy as np
np.random.seed(10)

import pandas as pd
from math import sqrt

def compute_sigma_coefficient(vec1, vec2):
    '''
    Input: Two vectors
    Output: If vectors are orthogonal, '0'; Else the coefficient for projection along the 2nd vector (i.e. vec2 = direction).
    
    Hint: You should probably error-check for division by zero before simply computing this!    
    '''
    
    b = np.array(vec1)
    v = np.array(vec2)
    
    
    dotP = np.dot(b, v) 
    if dotP == 0:
        return 0
    
    cross1 = v.T @ b
    cross2 = v.T @ v
    
    if cross2 == 0:
        return "error: div by 0"
    else:
        return cross1 / cross2
        
    

def project_along(vec1, vec2):
    '''
    Input: two vectors
    Output (return): the portion of vector 1, parallel to vector 2 (i.e. along)
    
    Hint: Use the function you computed above!    
    '''
    sigma = compute_sigma_coefficient(vec1, vec2) 
    return (sigma, sigma * np.array(vec2))

In [50]:
#Code to test your functions:
#Put some sample code here to test your function outputs. 

v = [[1/sqrt(6), 2/sqrt(6), 1/sqrt(6)],
     [1, 1, 2]]

print(5/6)

project_along(v[1], v[0])[1]

0.8333333333333334


array([0.83333333, 1.66666667, 0.83333333])

### Task 4.2 Computing the Orthogonal Projection

In [112]:
def gram_schmidt(vlist):
    S = []
    V = []
    vcopy = vlist.copy()
    
    u = vcopy.pop()
    V.append(u)
    S.append(1)
    
    for v in vcopy:
        s, vproj = project_along(u, v)
        u = u - vproj
        S.append(s)
        V.append(u)

    return (V, S)


def project_orthogonal(vec_b, vec_list):
    '''
    Input: 
        vec_b is a vector to orthogonalize
        vec_list is a list of vectors for vec_b to be orthogonal to
    
    Output (return): The portion of vec_b orthogonal to the vec_list
    
    Hint: Reuse the functions you've already defined!
    
    '''
    vec_list.append(vec_b)
    return gram_schmidt(vec_list)[0][-1]

In [113]:
#Code to test your function

import math

#Put some sample code here!
b = [1,1,2]
v = [[1/math.sqrt(6), 2/math.sqrt(6), 1/math.sqrt(6)],
     [-1/math.sqrt(2), 0, 1/math.sqrt(2)]]

b_perp_v = project_orthogonal(b, v)
b_perp_v

array([ 0.66666667, -0.66666667,  0.66666667])

### Task 4.3 Finding an orthogonal basis

In [115]:
def my_orthogonalize(vec_list):
    '''
    Input: a list of vectors
    Output (return): a list of mutually orthogonal vectors
    
    Hint: Reuse the functions you've already defined!
    '''
    return gram_schmidt(vec_list)[0]

In [116]:
#Code to test your function

# v = [[3, 1],
#      [2, 2]]

v = [[1/math.sqrt(6), 2/math.sqrt(6), 1/math.sqrt(6)],
     [-1/math.sqrt(2), 0, 1/math.sqrt(2)],
     [1, 1, 2]]

my_orthogonalize(v)

[[1, 1, 2],
 array([ 0.16666667, -0.66666667,  1.16666667]),
 array([ 0.66666667, -0.66666667,  0.66666667])]

In [117]:
[1/math.sqrt(6), 2/math.sqrt(6), 1/math.sqrt(2)]

[0.4082482904638631, 0.8164965809277261, 0.7071067811865475]

### Task 4.4 Extending your functions

Extend the functions "project_orthogonal" and then "my_orthogonalize" to return the coefficients used in the projections. Basically, you are returning additional things, so you can later (soon) make a QR decomposition.

In [118]:
def project_orthogonal_sigma(vec_b, vec_list):
    '''
    Input: 
        vec_b is a vector to orthogonalize
        vec_list is a list of vectors for vec_b to be orthogonal to
    
    Output (return): (vec_star, sigma_list)
        vec_star = The portion of vec_b orthogonal to the vec_list
        sigma_list = The sigmas, computed for each vector projection in vec_list
    
    '''
    vec_list.append(vec_b)
    V, S = gram_schmidt(vec_list)
    return V[-1], S

In [119]:
#Code to test your function

#Put some sample code here!

v = [[1/math.sqrt(6), 2/math.sqrt(6), 1/math.sqrt(6)],
     [-1/math.sqrt(2), 0, 1/math.sqrt(2)],
     [1, 1, 2]]

project_orthogonal_sigma(v[2], v[:2])

(array([ 0.66666667, -0.66666667,  0.66666667]),
 [1, 2.0412414523193148, 0.7071067811865476])

In [122]:
def my_orthogonalize_sigma(vec_list):
    '''
    Input: a list of vectors
    Output (return): (vec_star_list, sigma_vec_list)
        vec_star_list =  a list of mutually orthogonal vectors
        sigma_vec_list = A list of the sigma vectors, computed for each set of vector projections
    
    Hint: Reuse the functions you've already defined!
    '''
    
    U = []
    Smat = []
    
    for v in vec_list:
        vc = vec_list.copy()
        vc.remove(v)
        vc.append(v)
        (V, S) = gram_schmidt(vc)
        U.append(V[-1])
        Smat.append(S)
    
    return U, Smat

In [123]:
#Code to test your function

#Put some sample code here!

v = [[1/math.sqrt(6), 2/math.sqrt(6), 1/math.sqrt(6)],
     [-1/math.sqrt(2), 0, 1/math.sqrt(2)],
     [1, 1, 2]]
my_orthogonalize_sigma(v)

([array([ 0.06804138,  0.47628967, -0.27216553]),
  array([-0.82495791, -0.11785113,  0.47140452]),
  array([ 0.66666667, -0.66666667,  0.66666667])],
 [[1, 0, 0.34020690871988585],
  [1, 0, 0.1178511301977579],
  [1, 2.0412414523193148, 0.7071067811865476]])

### Task 4.5 Normalizing a vector

In [149]:
def norm_vec(vec):
    '''
    Input: a vector
    Output (return): (vec, factor)
    vec = scaled version of vector, such that norm(vec) = 1
    factor = scaling factor used on returned vector
    
    '''
    vec_array = np.array(vec)
    factor = np.linalg.norm(vec_array)
    return (vec_array / factor, factor)

norm_vec([1, 1, 2])

(array([0.40824829, 0.40824829, 0.81649658]), 2.449489742783178)

### Task 4.5 Finding a QR Factorization
Use the functions you've defined to construct a QR factorization of a matrix.
The psuedo-code looks like this:

def myqr(MatrixA):

    apply my_orthogonalize_sigma to MatrixA
    let Q = matrix with the set of vectors returned from my_orthogonalize, but normalized to 1
    let R = sigma coefficient matrix, with rows scaled by the normalization factor.

In [156]:
def myqr(MatrixA):
    '''
    Input: A Matrix
    Output (return) : (Q, R) where:
        Q is a matrix with orthonormal columns
        R is a triangular matrix, such that QR = A
    '''
    Q = []
    A = MatrixA.tolist()
    (V,_) = my_orthogonalize_sigma(A)
    
    for v in V:
        Q.append(norm_vec(v))
    
    Q = np.matrix(Q)

    return (Q, Q.T * MatrixA)


aT = [[1/math.sqrt(6), 2/math.sqrt(6), 1/math.sqrt(6)],
     [-1/math.sqrt(2), 0, 1/math.sqrt(2)],
     [1, 1, 2]]

q, r = myqr(np.matrix(aT))

print(q)
print()
print(r)

[[array([[ 0.12309149],
       [ 0.86164044],
       [-0.49236596]])
  0.5527707983925667]
 [array([[-0.86164044],
       [-0.12309149],
       [ 0.49236596]])
  0.957427107756338]
 [array([[ 0.57735027],
       [-0.57735027],
       [ 0.57735027]])
  1.1547005383792517]]

[[array([[ 1.23687396],
       [-0.13854821],
       [ 0.02818739]])
  array([[0.67785405],
       [0.1261762 ],
       [0.17533514]])
  array([[ 0.59568063],
       [-0.88997613],
       [ 1.30184829]])]
 [0.7033650714550319 1.606036005303472 3.2120720106069434]]


### Task - Challenge: Implement Solving a system of equations USING either QR (or LU).