In [87]:
# A = [[1., 0., 0., 0.],
#          [-.5, 1., 0., 0.],
#          [-.25, 0., 1., 0.], 
#          [-.75, 0., 0., 1.]]

# B = [[8., 7., 9., 5.],
#          [4., 3., 3., 1.],
#          [2., 1., 1., 0.], 
#          [6., 7., 9., 8.]]

# print(np.matrix(A)*np.matrix(B))

# f = np.matrix([[8., 7., 9., 5.],
#  [4., 3., 3., 1.],
#  [2., 1., 1., 0.],
#  [6., 7., 9., 8.]])

# g = np.matrix([[ 1.,    0.,    0.,    0.  ],
#  [-0.5,   1.,    0.,    0.,  ],
#  [-0.25,  0.,    1.,    0.,  ],
#  [-0.75,  0.,    0.,    1.,  ]])

# print(np.eye(4)*f)

[[ 8.    7.    9.    5.  ]
 [ 0.   -0.5  -1.5  -1.5 ]
 [ 0.   -0.75 -1.25 -1.25]
 [ 0.    1.75  2.25  4.25]]
[[8. 7. 9. 5.]
 [4. 3. 3. 1.]
 [2. 1. 1. 0.]
 [6. 7. 9. 8.]]


## Take-Home Final - Computational Linear Algebra 373/574

**Put my normal pre-exam stuff here**

This exam was complete by _Rikki Shomer_

_I have not given, recieved, nor tolerated others use of unauthorized aid on this exam._

## Problem 1 - (15 pts) Extending the LU Decomposition Methods:

### Part A 
(10pts) Modify the LU method from Rachel's lectures to add partial pivoting.  

*Hint: the swap method below will be useful. Don't forget to run the cell before using the function.*

**NOTE:** I am well aware that you can probably find LU with pivoting on Stack-Overflow. Two Comments:

    1) If you get code from stack-overflow... be absolutely sure it works.
    2) Make sure you MODIFY this function, that is, if you get whole-sale different code, I'll know it's not your work!

In [1]:
import numpy as np
import scipy.linalg as la

def LU(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
    return L, U

In [2]:
#Don't forget to run this cell before using this function.
def swap(a,b):
    temp = np.copy(a)
    a[:] = b
    b[:] = temp

In [96]:
def LU_piv(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    P = np.copy(L)
    
    #Missing all the real code!
    for k in range(n-1):
        L_inc = np.eye(n)
        
        #find largest element in column below diagonal
        pivot_idx = np.argmax(U[k+1:,k]) + k + 1
        pivot = U[pivot_idx,k]
        
        #swap with pivot row
        swap(P[k], P[pivot_idx])
        swap(U[k], U[pivot_idx])
        
        #needs to be swapped with the prior L(k-1)
        if (k > 0):
            swap(L[k,:k], L[pivot_idx,:k])
        
        elim_vals = np.copy(U[k+1:,k]/pivot).flatten()
        L[k+1:,k] = elim_vals
        L_inc[k+1:,k] = -elim_vals

        U = np.matrix(L_inc)*U
        
    return np.matrix(P), np.matrix(L), np.matrix(U)

In [97]:
#Cell for including some test code of your LU with pivoting.

Alist = [[2., 1., 1., 0.],
         [4., 3., 3., 1.],
         [8., 7., 9., 5.], 
         [6., 7., 9., 8.]]
A = np.matrix(Alist)
# scratch to test my array kerfuffle
# ac = np.copy(A)
# ac = ac[2:4,2] * ac[2:4,2]
# print(ac)

print("----------Full--------------\n")
L,U = LU(A)
print(L)
print(U)

print("\n\n----------Pivot-------------\n")

P,L2,U2 = LU_piv(A)
print(P)
print(L2)
print(U2)

Atest = P.T*L2*U2

print(np.allclose(Atest, A))

----------Full--------------

[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]
[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]


----------Pivot-------------

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
True


### Part B
(5 pts) Provide a **WRITTEN** explanation of how to modify your above algorithm to implement full pivoting. You do NOT need to code this (though you might want to, to confirm it works like you think it will). This should clearly be how to MODIFY YOUR EXISTING CODE. It should not simply be an explanation of what "full pivoting" is, though it should be clear from your explanation that you understand what full pivoting is.

In [4]:
#Cell to test (if needed) your full-pivot LU.

## Problem 2: (5 pts each) Storage Formats
Given the matrix:

\begin{pmatrix}
  1 & & & & -2 & -3 \\
  & 3 &  & & & -9 \\
  &  &  & -7 & 4 & \\ 
  -1 & 2 & & 7 & & \\
  -3 & & & 26 & &
 \end{pmatrix}
 
### Part A -- Write how this matrix would be stored in compressed **row** format.
### Part B -- Write how this matrix would be stored in compressed **column** format.
### Part C -- Write how this matrix would be stored in coordinate format.

### Problem 2 Answers:

Parts A through C above all requisite we compute the SVD of the Given matrix A.
Let us define the SVD matrix A to be: 

$A =U \Sigma V_t$

Where $A$ is the given matrix.  $U$ and $V$ are unitary matrics whose columns represent the eigenvectors of $A$, and $\Sigma$ is a diagonal matrix whose values along the diagonal elements correspond to the eigenvalues of matrix $A$.  We also state $\Sigma_v$ to be the vector of diagonal values in $\Sigma$

(_note_: $V_t$ is then said to have orthogonal ROW vectors) 


It follows then that we would be able to store a compressed version of the image with...
    
**Part A)**  
...respect to its column space by simply storing $U$ and $\Sigma_v$ 

**Part B)**  
...respect to its row space by simply storing $V_t$ and $\Sigma_v$  

**Part C)**  
asfdds 

## Problem 3 - (30pts) Applying Least-Squares to real data.

Below is a code-snippet that imports some hospital data, reduces it to the numerical attributes, then shows you the data summary and head of the files. Run this code snippet, examine the results, then look afterwards for the questions to answer.

This data was retrieved from the CORGIS project: https://think.cs.vt.edu/corgis/csv/hospitals/hospitals.html

In [99]:
import pandas as pd
import numpy as np
#Read in the hospital data
hospitals = pd.read_csv('hospitals.csv')
#If you want to look at the full data-set you can.
#print(hospitals.keys())
#print(hospitals.describe())
#print(hospitals.head())

hospitals_reduced = hospitals.copy() #Make a copy to drop columns not needed for least squares fitting. 
hospitals_reduced = hospitals_reduced.drop(['Address', 'County', 'City', 'Phone Number', 'Ownership', 'Provider ID', 'State', 'Type', 'ZIP Code', 'Name', 'Longitude', 'Emergency Services', 'Latitude'], axis=1)

#Turn it into a numpy array
hospital_reduced_array = np.array(hospitals_reduced)

#Output some summaries and data
print("Variable/Key Names in the (Reduced) Dataset:\n", hospitals_reduced.keys(), "\n")
print("Summary Statistics: \n", hospitals_reduced.describe(), "\n")
print("Shape of data matrix: ", np.shape(hospital_reduced_array))

print("\n \n ---------------- \n \n")
print("First 5 lines of the pandas data-frame:\n", hospitals_reduced.head(), "\n")
print("Output of the numpy array:\n", hospital_reduced_array, "\n")


Variable/Key Names in the (Reduced) Dataset:
 Index(['Cardiovascular', 'Eye', 'Gastrointestinal', 'Genitourinary',
       'Musculoskeletal', 'Nervous System', 'Skin'],
      dtype='object') 

Summary Statistics: 
        Cardiovascular            Eye  Gastrointestinal  Genitourinary  \
count     4861.000000    4861.000000       4861.000000    4861.000000   
mean       609.459782     258.626209       1361.990125     285.108825   
std      11366.625942    4971.204240       3359.573371    1111.837436   
min          0.000000       0.000000          0.000000       0.000000   
25%          0.000000       0.000000          0.000000       0.000000   
50%          3.000000       0.000000        160.000000      13.000000   
75%        183.000000     136.000000       1578.000000     263.000000   
max     709791.000000  344180.000000     136890.000000   51083.000000   

       Musculoskeletal  Nervous System          Skin  
count      4861.000000     4861.000000   4861.000000  
mean        520.42

Using the hospital data, perform a least-squares fit of two models for the relationship between 'Cardiovascular' operations and the other specializations. Some sklearn code is used below to provide you with test and training data split, as well as the target variables (split for training and testing).

Model 1: Cardio (dependent variable) is related to the others using only FIRST-ORDER relationships (i.e. linear)

Model 2: Cardio (dependent variable) is related to the others using FIRST and SECOND order relationships

***Hint:*** *If you are stuck, look at the USF Notebook 5 and Videos CLA-8 S1+S2 for some hints on several of the sub-part below. This is an expansion on some of those processes, applied to a different data-set. You can resuse code from the USF Notebooks when appropriate*

In [100]:
from sklearn import datasets, linear_model, metrics
from sklearn.model_selection import train_test_split

hospital_features_trn,hospital_features_test,hospital_target_trn,hospital_target_test = train_test_split(hospital_reduced_array[:,1:7], hospital_reduced_array[:,0], test_size=0.2)
hospital_features_trn.shape, hospital_features_test.shape

((3888, 6), (973, 6))

### Problem 3 - Model Definitions

In [120]:
#Train and test the log reg   
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import PolynomialFeatures

import math

def error_foo(test, pred):
    return (math.sqrt(mean_squared_error(test, pred)), 
            mean_absolute_error(test, pred))

def display_Ls(test, pred):
    (L2, L1) = error_foo(test, pred)
    print("\nmean absolute error (L1):  ", L1)
    print("mean squared norm (L2):  ", L2, "\n")

    

    
lr = LinearRegression()
%time lr.fit(hospital_features_trn, hospital_target_trn)

hospital_target_pred = lr.predict(hospital_features_test)
display_Ls(hospital_target_test, hospital_target_pred)

pr = LinearRegression()
poly = PolynomialFeatures(include_bias=False)
poly_fts_trn = poly.fit_transform(hospital_features_trn)

%time pr.fit(poly_fts_trn, hospital_target_trn)

poly_fts_test = poly.fit_transform(hospital_features_test)
hospital_target_pred2 = pr.predict(poly_fts_test)
display_Ls(hospital_target_test, hospital_target_pred2)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.16 ms

mean absolute error (L1):   2395.39480042762
mean squared norm (L2):   6617.439527839677 

CPU times: user 15.6 ms, sys: 15.6 ms, total: 31.2 ms
Wall time: 3.68 ms

mean absolute error (L1):   2466.32764622198
mean squared norm (L2):   29740.644488364676 



### Part A -- Finding Decompositions -- 3 pts per model, per decomposition.

Find the coefficients for both of these models using (Turn in the code, I recommend separate code-cells for each):

    (a) A LU Decomposition
    (b) A QR Decomposition
    (c) A SVD Decomposition

**NOTE: You do NOT need to write or use your own functions for these! You may use optimized/packaged routines. You do however need to provide code, including the package imports, of how to make use of standard routines.**

**NOTE 2: You should try to only use packages that are installed in the base install of Anaconda, eg: numpy, pandas, sklearn, scipy, math etc.**

#### Part A - Model 1

In [159]:
print(lr.coef_)
data_matrix = hospital_reduced_array[:,1:7]
target = hospital_reduced_array[:, 0]

# (a) A LU Decomposition

import scipy.linalg as la

p,l,u = la.lu(data_matrix)
pb = p * np.matrix(target).T
y = la.lstsq(l,pb)[0]
lu_coefs = la.solve_triangular(u,y)
print(lu_coefs.flatten())


# (b) A QR Decomposition



# (c) A SVD Decomposition
u, s, vt = la.svd(data_matrix)

#A = USVt => b = USVt*x => Ut*b = SVt*x => (Ut*b)/S = Vt*x =>  (Vt)t*((Ut*b)/S) = x

t1 = (u.T*target)
# t2 = t1/s
# svd_coefs = vt.T*t2
# print(svd_coefs)
def ls_svd(A,b):
    m, n = A.shape
    U, sigma, Vh = la.svd(A, full_matrices=False, lapack_driver='gesdd')
    w = (U.T @ b)/ sigma
    return Vh.T @ w


print(ls_svd(data_matrix,target))

[ 4.11494962e-05 -1.30299043e+00  7.33727131e-01 -3.31861841e-02
  5.52223942e+00  8.17685717e-01]
[-0.00820285 -1.11528834  0.98284636 -0.48919536  5.2417941   0.56546641]
[-0.00820285 -1.11528834  0.98284636 -0.48919536  5.2417941   0.56546641]


#### Part A - Model 2

In [ ]:
print(pr.coef_)


### Part B -- Analysis of Outputs -- 6 pts each
This quesiton will be graded on the quality of your explanations/comparisons, not on the accuracy (besides use of your numbers from above).

Report in paragraphs explaining how to interpret the results:

  1) A comparison of the time for each model, using each solution technique.
  
  The linear model (Model1) was fairly quick to execute as it only required approximately 10.6 ms.  However, the second order model (Model2) required ms.
  
  2) A comparison of the L1 & L2 accuracy, using each solution technique. 
  
  

## Bonus Problem (10 pts) Add shifts to the QR algorithm

Instead of factoring $A_k$ as $Q_k R_k$ (the way the pure QR algorithm without shifts does), the shifted QR algorithm:

i. Chooses/Finds $s_k = A_k(m,m)$, an approximation of an eigenvalue of A.

ii. Gets the QR factorization $$A_k - s_k I = Q_k R_k$$

iii. Sets $$A_{k+1} = R_k Q_k + s_k I$$

*Hint: If you aren't sure how to get an eigenvalue approximation, one option is to look back at the truncated/randomized SVD processes. What's the relationship between the first singular value in that process and the eigenvalues of A? What is the relationship between SVD and QR?*

The idea of adding shifts to speed up convergence shows up in many algorithms in numerical linear algebra (including the power method, inverse iteration, and Rayleigh quotient iteration).  The real way this would work is through using additional mathematics of Hessenberg matrices and Householder transformations (from which the eigen-value approximations come as part of the iterative process).

In [ ]:
def practical_qr(A, iters=10):
    # Fill method in
    return Ak, Q