In [7]:
import numpy as np
import scipy as sp
from scipy import linalg

In [2]:
flowers = np.array([[1, 1, 10],[2, 1, 12], [2, 2, 15], [3, 2, 17]])
print(flowers)

[[ 1  1 10]
 [ 2  1 12]
 [ 2  2 15]
 [ 3  2 17]]


In [8]:
u, s, vt = linalg.svd(flowers)
print(u)
print(s)
print(vt)

[[-0.35992497 -0.64948244  0.44567542  0.5       ]
 [-0.43537256  0.32057846  0.67652065 -0.5       ]
 [-0.54453842 -0.43556862 -0.51357364 -0.5       ]
 [-0.61998601  0.53449227 -0.28272841  0.5       ]]
[ 28.02174538   0.74189317   0.48102034]
[[-0.14915934 -0.11149721 -0.98250693]
 [ 0.97590067 -0.17665169 -0.12810956]
 [-0.15927765 -0.97793791  0.13515945]]
